// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuOuwphflE59rA20fB-9FpM9xZSkvx5x8',
    appId: '1:126981167677:web:07787efd57f3e935722854',
    messagingSenderId: '126981167677',
    projectId: 'freedom-346912',
    authDomain: 'freedom-346912.firebaseapp.com',
    storageBucket: 'freedom-346912.appspot.com',
    measurementId: 'G-CDZF66NT64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuTPoEkkaVaBUVTduvCGAgMifaDaK_rqM',
    appId: '1:126981167677:android:a71b19da68e0f3dd722854',
    messagingSenderId: '126981167677',
    projectId: 'freedom-346912',
    storageBucket: 'freedom-346912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBonDVQ8PTt2S6J7Jw2Wk9fxzKsxLJ6tVY',
    appId: '1:126981167677:ios:474e7ee8dc2e6fe8722854',
    messagingSenderId: '126981167677',
    projectId: 'freedom-346912',
    storageBucket: 'freedom-346912.appspot.com',
    iosClientId: '126981167677-f2uqbaip3p3h79n9bh9kf7g85k4oeqi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
